language: python
python: 3.6
services: docker
script:
- PATH=$PATH:$PWD/cli/bin ci/run_tests
- docker build -t falsifiable/popper cli/
- docker run --rm -e CI=1 -e POPPER_FIGSHARE_API_TOKEN="${POPPER_FIGSHARE_API_TOKEN}" -e POPPER_ZENODO_API_TOKEN="${POPPER_ZENODO_API_TOKEN}" -e POPPER_GITHUB_API_TOKEN="${POPPER_GITHUB_API_TOKEN}" -v `pwd`/ci/run_tests:/run_tests --entrypoint=/run_tests falsifiable/popper
